import type { ProfileResult } from "@/lib/types";
import type { ExportUserInput } from "@/lib/services/export-generator";
import { createBasePdf, addPage, wrapText, sanitizeForPdf, COLORS } from "./shared";

/**
 * Generate a Cover Letter PDF.
 *
 * Simple, polished layout:
 * - Title + date
 * - Optional recipient line (from job description)
 * - Body paragraphs from results.coverLetter.content
 * - Footer
 */
export async function generateCoverLetterPdf(
  results: ProfileResult,
  language: string,
  userInput?: ExportUserInput
): Promise<Uint8Array> {
  const { doc, fontRegular, fontBold } = await createBasePdf();
  const margin = 50;
  const pageWidth = 595.28;
  const contentWidth = pageWidth - margin * 2;

  let page = addPage(doc);
  let y = page.getHeight() - margin;

  // ── Title ──
  const title =
    language === "es" ? "Carta de Presentacion" : "Cover Letter";
  page.drawText(sanitizeForPdf(title), {
    x: margin,
    y,
    size: 20,
    font: fontBold,
    color: COLORS.primary,
  });
  y -= 18;

  // ── Date line ──
  const dateStr = new Date().toLocaleDateString(
    language === "es" ? "es-ES" : "en-US",
    { year: "numeric", month: "long", day: "numeric" }
  );
  page.drawText(sanitizeForPdf(dateStr), {
    x: margin,
    y,
    size: 9,
    font: fontRegular,
    color: COLORS.textMuted,
  });
  y -= 25;

  // ── Target role context (if available) ──
  if (userInput?.jobDescription) {
    const targetLine = userInput.jobDescription.split("\n")[0]?.trim().slice(0, 120);
    if (targetLine) {
      const targetLabel =
        language === "es" ? "Puesto objetivo:" : "Target role:";
      page.drawText(sanitizeForPdf(`${targetLabel} ${targetLine}`), {
        x: margin,
        y,
        size: 9,
        font: fontRegular,
        color: COLORS.textMuted,
      });
      y -= 18;
    }
  }

  // Divider
  page.drawLine({
    start: { x: margin, y },
    end: { x: pageWidth - margin, y },
    thickness: 0.5,
    color: COLORS.border,
  });
  y -= 25;

  // ── Body ──
  const content = results.coverLetter?.content ?? "";

  if (!content.trim()) {
    const noContent =
      language === "es"
        ? "No se genero una carta de presentacion para este perfil."
        : "No cover letter was generated for this profile.";
    page.drawText(sanitizeForPdf(noContent), {
      x: margin,
      y,
      size: 11,
      font: fontRegular,
      color: COLORS.textMuted,
    });
  } else {
    const paragraphs = content.split("\n");

    for (const para of paragraphs) {
      // Empty lines create paragraph spacing
      if (!para.trim()) {
        y -= 10;
        continue;
      }

      const lines = wrapText(sanitizeForPdf(para), fontRegular, 11, contentWidth);
      for (const line of lines) {
        if (y < 60) {
          page = addPage(doc);
          y = page.getHeight() - margin;
        }
        page.drawText(line, {
          x: margin,
          y,
          size: 11,
          font: fontRegular,
          color: COLORS.text,
        });
        y -= 16;
      }
      y -= 6; // paragraph spacing
    }
  }

  // ── Footer ──
  const lastPage = doc.getPages()[doc.getPageCount() - 1];
  const footerText =
    language === "es"
      ? "Generado por Profile Score"
      : "Generated by Profile Score";
  lastPage.drawText(sanitizeForPdf(footerText), {
    x: margin,
    y: 30,
    size: 8,
    font: fontRegular,
    color: COLORS.textMuted,
  });

  return doc.save();
}
