import type { ProfileResult, RewritePreview } from "@/lib/types";
import { getSectionLabel } from "@/lib/section-labels";
import { createBasePdf, addPage, wrapText, sanitizeForPdf, COLORS } from "./shared";
import { sanitizeTemplateOutput } from "@/lib/utils/placeholder-detect";
import { rgb } from "pdf-lib";

import en from "@/lib/i18n/en.json";
import es from "@/lib/i18n/es.json";

const i18nMap: Record<string, Record<string, string>> = {
  en: (en as Record<string, unknown>).sectionLabels as Record<string, string>,
  es: (es as Record<string, unknown>).sectionLabels as Record<string, string>,
};

// Ordered LinkedIn section IDs for display
const LINKEDIN_SECTION_ORDER = [
  "headline", "summary", "experience", "education", "skills",
  "certifications", "recommendations", "featured", "projects",
  "volunteer", "honors", "publications",
];

// LinkedIn-style colors
const LI_BLUE = rgb(0.04, 0.4, 0.76);      // #0a66c2
const LI_BG_GRAY = rgb(0.95, 0.95, 0.94);  // #f3f2ef
const LI_TEXT_DARK = rgb(0.0, 0.0, 0.0);
const LI_TEXT_GRAY = rgb(0.38, 0.38, 0.38); // #616161
const LI_TEXT_LIGHT = rgb(0.55, 0.55, 0.55);
const LI_BORDER = rgb(0.88, 0.88, 0.88);

/**
 * PHASE 4.2: Generate a LinkedIn Updates PDF — LinkedIn Profile Page Style
 *
 * Layout mimics a printed LinkedIn profile:
 * - Light gray header band with name (24pt bold) + headline (14pt)
 * - Section titles 16pt bold with left blue accent bar
 * - Entry-level: Company bold → Position → Date range → Bullets
 * - Clean sans-serif (Helvetica = LinkedIn-like)
 * - Footer: "Generated by ProfileScore.io — Copy-paste ready for LinkedIn"
 */
export async function generateLinkedinUpdatesPdf(
  results: ProfileResult,
  language: string
): Promise<Uint8Array> {
  const { doc, fontRegular, fontBold } = await createBasePdf();
  const labels = i18nMap[language] ?? i18nMap.en;
  const margin = 50;
  const pageWidth = 612; // US Letter
  const contentWidth = pageWidth - margin * 2;

  let page = addPage(doc);
  let y = page.getHeight() - margin;

  // ── Helpers ──
  function ensureSpace(needed: number) {
    if (y < needed) {
      page = addPage(doc);
      y = page.getHeight() - margin;
    }
  }

  // ── Order and filter rewrites ──
  const rewrites = LINKEDIN_SECTION_ORDER
    .map((id) => results.linkedinRewrites.find((r) => r.sectionId === id))
    .filter((r): r is RewritePreview => r != null)
    .filter((r) => !r.locked);

  const orderedIds = new Set(LINKEDIN_SECTION_ORDER);
  const extraRewrites = results.linkedinRewrites.filter(
    (r) => !orderedIds.has(r.sectionId) && !r.locked
  );
  const allRewrites = [...rewrites, ...extraRewrites];

  // ── Header band: Light gray background ──
  const headerHeight = 100;
  page.drawRectangle({
    x: 0,
    y: page.getHeight() - headerHeight,
    width: pageWidth,
    height: headerHeight,
    color: LI_BG_GRAY,
  });

  // Extract name from headline or contact
  const headlineRewrite = allRewrites.find((r) => r.sectionId === "headline");
  const headlineText = headlineRewrite
    ? sanitizeForPdf(sanitizeTemplateOutput(headlineRewrite.rewritten))
    : "";

  // Name: 24pt bold
  const nameText = extractNameFromResults(results) || "Your Name";
  y = page.getHeight() - margin - 10;
  page.drawText(sanitizeForPdf(nameText), {
    x: margin,
    y,
    size: 24,
    font: fontBold,
    color: LI_TEXT_DARK,
  });
  y -= 28;

  // Headline: 14pt normal, dark gray
  if (headlineText) {
    const headlineLines = wrapText(headlineText, fontRegular, 14, contentWidth);
    for (const line of headlineLines.slice(0, 2)) {
      page.drawText(line, {
        x: margin,
        y,
        size: 14,
        font: fontRegular,
        color: LI_TEXT_GRAY,
      });
      y -= 18;
    }
  }
  y -= 10;

  // Location + date line
  const dateStr = new Date().toLocaleDateString(
    language === "es" ? "es-ES" : "en-US",
    { year: "numeric", month: "long", day: "numeric" }
  );
  page.drawText(sanitizeForPdf(dateStr), {
    x: margin,
    y,
    size: 9,
    font: fontRegular,
    color: LI_TEXT_LIGHT,
  });
  y -= 25;

  if (allRewrites.length === 0) {
    const noContent = language === "es"
      ? "No hay secciones optimizadas disponibles."
      : "No optimized sections available.";
    page.drawText(sanitizeForPdf(noContent), {
      x: margin,
      y,
      size: 11,
      font: fontRegular,
      color: LI_TEXT_GRAY,
    });
  }

  for (const rewrite of allRewrites) {
    if (!rewrite) continue;
    // Skip headline — already rendered in header
    if (rewrite.sectionId === "headline") continue;

    ensureSpace(120);

    const label = getSectionLabel(rewrite.sectionId, labels);

    // ── Section heading with left blue accent bar ──
    // Blue accent bar (3px wide, LinkedIn blue)
    const sectionTitleHeight = 18;
    page.drawRectangle({
      x: margin - 2,
      y: y - 2,
      width: 3,
      height: sectionTitleHeight,
      color: LI_BLUE,
    });

    // Section title: 16pt bold
    page.drawText(sanitizeForPdf(label), {
      x: margin + 8,
      y,
      size: 16,
      font: fontBold,
      color: LI_TEXT_DARK,
    });
    y -= 24;

    // ── Entry-level rendering (experience/education) ──
    if (rewrite.entries && rewrite.entries.length > 0) {
      for (let entryIndex = 0; entryIndex < rewrite.entries.length; entryIndex++) {
        const entry = rewrite.entries[entryIndex];
        ensureSpace(100);

        // Separator between entries
        if (entryIndex > 0) {
          y -= 4;
          page.drawLine({
            start: { x: margin + 8, y: y + 4 },
            end: { x: pageWidth - margin, y: y + 4 },
            thickness: 0.5,
            color: LI_BORDER,
          });
          y -= 10;
        }

        // Structured entry rendering
        if (entry.organization) {
          // Company name (bold, 11pt)
          const orgLines = wrapText(sanitizeForPdf(entry.organization), fontBold, 11, contentWidth - 8);
          for (const line of orgLines) {
            ensureSpace(50);
            page.drawText(line, { x: margin + 8, y, size: 11, font: fontBold, color: LI_TEXT_DARK });
            y -= 15;
          }

          // Position title (regular, 10pt, gray)
          if (entry.title) {
            const titleLines = wrapText(sanitizeForPdf(entry.title), fontRegular, 10, contentWidth - 8);
            for (const line of titleLines) {
              ensureSpace(50);
              page.drawText(line, { x: margin + 8, y, size: 10, font: fontRegular, color: LI_TEXT_GRAY });
              y -= 14;
            }
          }

          // Date range (smaller, lighter)
          if (entry.dateRange) {
            ensureSpace(40);
            page.drawText(sanitizeForPdf(entry.dateRange), { x: margin + 8, y, size: 9, font: fontRegular, color: LI_TEXT_LIGHT });
            y -= 12;
          }
        } else {
          // Fallback regex-based parsing
          const titleText = sanitizeForPdf(entry.entryTitle);
          const atMatch = titleText.match(/^(.+?)\s+at\s+(.+)$/i);
          const enMatch = titleText.match(/^(.+?)\s+en\s+(.+)$/i);
          const parsed = atMatch ?? enMatch;

          if (parsed) {
            for (const line of wrapText(parsed[2].trim(), fontBold, 11, contentWidth - 8)) {
              ensureSpace(50);
              page.drawText(line, { x: margin + 8, y, size: 11, font: fontBold, color: LI_TEXT_DARK });
              y -= 15;
            }
            for (const line of wrapText(parsed[1].trim(), fontRegular, 10, contentWidth - 8)) {
              ensureSpace(50);
              page.drawText(line, { x: margin + 8, y, size: 10, font: fontRegular, color: LI_TEXT_GRAY });
              y -= 14;
            }
          } else {
            for (const line of wrapText(titleText, fontBold, 11, contentWidth - 8)) {
              ensureSpace(50);
              page.drawText(line, { x: margin + 8, y, size: 11, font: fontBold, color: LI_TEXT_DARK });
              y -= 16;
            }
          }

          // Extract date from original text (fallback)
          if (!entry.dateRange) {
            const originalFirstLine = entry.original.split("\n").find((l) => l.trim().length > 0)?.trim() ?? "";
            const dateLocMatch = originalFirstLine.match(
              /^(?:(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec|Ene|Abr|Ago|Dic)[a-z]*\.?\s+\d{4}|(?:19|20)\d{2})\s*[-\u2013]\s*(?:Present|Actual|(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec|Ene|Abr|Ago|Dic)[a-z]*\.?\s+\d{4}|(?:19|20)\d{2})(?:\s*[|,]\s*.+)?$/i
            );
            if (dateLocMatch) {
              ensureSpace(40);
              page.drawText(sanitizeForPdf(dateLocMatch[0]), { x: margin + 8, y, size: 9, font: fontRegular, color: LI_TEXT_LIGHT });
              y -= 12;
            }
          }
        }

        y -= 4;

        // Entry rewritten content
        const cleanedEntryRewritten = sanitizeTemplateOutput(entry.rewritten);
        for (const para of cleanedEntryRewritten.split("\n").filter(Boolean)) {
          const lines = wrapText(sanitizeForPdf(para), fontRegular, 10, contentWidth - 16);
          for (const line of lines) {
            ensureSpace(50);
            page.drawText(line, { x: margin + 12, y, size: 10, font: fontRegular, color: LI_TEXT_DARK });
            y -= 13;
          }
          y -= 2;
        }
        y -= 14;
      }
    } else {
      // ── Section-level rendering ──
      const cleanedSectionRewritten = sanitizeTemplateOutput(rewrite.rewritten);
      for (const para of cleanedSectionRewritten.split("\n").filter(Boolean)) {
        const lines = wrapText(sanitizeForPdf(para), fontRegular, 11, contentWidth - 8);
        for (const line of lines) {
          ensureSpace(50);
          page.drawText(line, { x: margin + 8, y, size: 11, font: fontRegular, color: LI_TEXT_DARK });
          y -= 14;
        }
        y -= 4;
      }
    }

    y -= 20; // generous spacing between sections
  }

  // ── Footer ──
  ensureSpace(40);
  y -= 10;
  page.drawLine({
    start: { x: margin, y: y + 8 },
    end: { x: pageWidth - margin, y: y + 8 },
    thickness: 0.5,
    color: LI_BORDER,
  });
  const footerText = language === "es"
    ? "Generado por ProfileScore.io - Listo para copiar y pegar en LinkedIn"
    : "Generated by ProfileScore.io - Copy-paste ready for LinkedIn";
  page.drawText(sanitizeForPdf(footerText), {
    x: margin,
    y: y - 5,
    size: 8,
    font: fontRegular,
    color: LI_TEXT_LIGHT,
  });
  const footerDate = dateStr;
  page.drawText(sanitizeForPdf(footerDate), {
    x: pageWidth - margin - fontRegular.widthOfTextAtSize(sanitizeForPdf(footerDate), 8),
    y: y - 5,
    size: 8,
    font: fontRegular,
    color: LI_TEXT_LIGHT,
  });

  return doc.save();
}

/**
 * Extract user name from ProfileResult.
 * Checks contact-info section in CV/LinkedIn rewrites.
 */
function extractNameFromResults(results: ProfileResult): string | null {
  // Check CV contact-info
  const cvContact = results.cvRewrites.find((r) => r.sectionId === "contact-info");
  if (cvContact) {
    const firstLine = sanitizeTemplateOutput(cvContact.rewritten).split("\n")[0]?.trim();
    if (firstLine && firstLine.length > 0 && firstLine.length < 60) return firstLine;
  }
  // Check LinkedIn headline for name-like content (less reliable)
  return null;
}

// Module-scoped date string for footer
const dateStr = new Date().toLocaleDateString("en-US", {
  year: "numeric",
  month: "long",
  day: "numeric",
});
