import type { ProfileResult } from "@/lib/types";
import { getSectionLabel } from "@/lib/section-labels";
import { createBasePdf, addPage, wrapText, sanitizeForPdf, COLORS } from "./shared";

import en from "@/lib/i18n/en.json";
import es from "@/lib/i18n/es.json";

const i18nMap: Record<string, Record<string, string>> = {
  en: (en as Record<string, unknown>).sectionLabels as Record<string, string>,
  es: (es as Record<string, unknown>).sectionLabels as Record<string, string>,
};

// Ordered CV section IDs for ATS-friendly layout
const CV_SECTION_ORDER = [
  "contact-info",
  "professional-summary",
  "work-experience",
  "skills-section",
  "education-section",
  "certifications",
];

export async function generateUpdatedCvPdf(
  results: ProfileResult,
  language: string
): Promise<Uint8Array> {
  const { doc, fontRegular, fontBold } = await createBasePdf();
  const labels = i18nMap[language] ?? i18nMap.en;
  const margin = 50;
  const pageWidth = 595.28;
  const contentWidth = pageWidth - margin * 2;

  let page = addPage(doc);
  let y = page.getHeight() - margin;

  // Title
  const title = language === "es" ? "CV Actualizado" : "Updated CV";
  page.drawText(sanitizeForPdf(title), {
    x: margin,
    y,
    size: 20,
    font: fontBold,
    color: COLORS.primary,
  });
  y -= 35;

  // Order rewrites by section order
  const orderedRewrites = CV_SECTION_ORDER.map((id) =>
    results.cvRewrites.find((r) => r.sectionId === id)
  ).filter(Boolean);

  for (const rewrite of orderedRewrites) {
    if (!rewrite) continue;

    if (y < 120) {
      page = addPage(doc);
      y = page.getHeight() - margin;
    }

    // Section heading
    const label = getSectionLabel(rewrite.sectionId, labels);
    page.drawText(sanitizeForPdf(label.toUpperCase()), {
      x: margin,
      y,
      size: 12,
      font: fontBold,
      color: COLORS.primary,
    });
    y -= 5;

    // Underline
    page.drawLine({
      start: { x: margin, y },
      end: { x: pageWidth - margin, y },
      thickness: 0.5,
      color: COLORS.border,
    });
    y -= 15;

    // Rewritten content
    const paragraphs = rewrite.rewritten.split("\n").filter(Boolean);
    for (const para of paragraphs) {
      const lines = wrapText(sanitizeForPdf(para), fontRegular, 10, contentWidth);
      for (const line of lines) {
        if (y < 50) {
          page = addPage(doc);
          y = page.getHeight() - margin;
        }
        page.drawText(line, {
          x: margin,
          y,
          size: 10,
          font: fontRegular,
          color: COLORS.text,
        });
        y -= 14;
      }
      y -= 4;
    }
    y -= 15;
  }

  // Footer
  const footerText =
    language === "es"
      ? "Generado por Profile Score"
      : "Generated by Profile Score";
  page.drawText(sanitizeForPdf(footerText), {
    x: margin,
    y: 30,
    size: 8,
    font: fontRegular,
    color: COLORS.textMuted,
  });

  return doc.save();
}
